/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempoexecucao;

/**
 *
 * @author Gilberto Toledo
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        c_tempo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Teste 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Teste 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Teste 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Teste 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tempo:");

        c_tempo.setText(" ");

        console.setColumns(20);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel1)
                    .addComponent(c_tempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        titulo.setText("GERAR 30 MIL NUMEROS SEQUENCIAIS");
        double inicio = System.currentTimeMillis();
        String saida = "";
        
        for(int i=1;i<=30000;i++){
            saida+= i+"\n";
        }
        
        console.setText(saida);
        double fim = System.currentTimeMillis();
        c_tempo.setText(String.format("%2.5f",(fim-inicio)/1000) );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        titulo.setText("GERAR 30 MIL NÚMEROS ALEATÓRIOS DE 0 A 50 MIL COM REPETIÇÃO");
        double inicio = System.currentTimeMillis();
        String saida = "";
        
        int i;        
        int numeros[] = new int[30000];
        int numero;
        for(i=0;i<30000;i++){
            numero = (int) (1 + Math.random() * 50000); // gera um valor randomico de 0.0 ate menores q 1.0, multiplica por 50000 e soma 1. Convertendo o resultado para int.
            numeros[i] = numero;
            saida += numero+"\n";
        }
        
        console.setText(saida);
        double fim = System.currentTimeMillis();
        c_tempo.setText(String.format("%2.5f",(fim-inicio)/1000) );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        titulo.setText("GERAR 30 MIL NÚMEROS ALEATÓRIOS DE 0 A 50 MIL SEM REPETIÇÃO");
        double inicio = System.currentTimeMillis();
        String saida = "";
                
        int i, j, existe;        
        int numeros[] = new int[30000];
        int numero;
        for(i=0;i<30000;i++){
            do{
                numero = (int) (1 + Math.random() * 50000); // gera um valor randomico de 0.0 ate menores q 1.0, multiplica por 50000 e soma 1. Convertendo o resultado para int.
                existe = 0; //0 -> NÃO EXISTE |  1 -> EXISTE
                for(j=0;j<i;j++){
                    if(numeros[j]==numero){
                        existe = 1;
                        break;
                    }
                }
            }while(existe==1);

            numeros[i] = numero;
            saida += numero+"\n";
        }
        
        console.setText(saida);
        double fim = System.currentTimeMillis();
        c_tempo.setText(String.format("%2.5f",(fim-inicio)/1000) );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        titulo.setText("GERAR OS PRIMEIROS 10 MIL NUMEROS PRIMOS");
        double inicio = System.currentTimeMillis();
        String saida = "";
        
        int numeros[] = new int[10000];
        int numero, primo;
        int i, j, divisores;
        numero = 2;
        for (i = 0; i < 10000; i++) {
            do{
                divisores = 0;
                for (j = 1; j <= numero; j++) {
                    if (numero % j == 0) {
                        divisores++;
                    }
                    if(divisores>2)
                        break;
                }
                if(divisores>2){
                    primo=0;
                    numero++;
                }else{
                    primo=1;
                }
            }while(primo==0);//0 -> NÃO PRIMO |  1 -> PRIMO
            numeros[i] = numero;
            saida += numero+"\n";
            numero++;
        }
        
        
        console.setText(saida);
        double fim = System.currentTimeMillis();
        c_tempo.setText(String.format("%2.5f",(fim-inicio)/1000) );
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c_tempo;
    private javax.swing.JTextArea console;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
